name: Sync Course Materials to Website

on:
  push:
    branches:
      - master
    paths:
      - 'course-materials/**'
      - 'docs/**'
      - 'templates/**'
      - 'resources/**'
  workflow_dispatch:

jobs:
  sync-to-website:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout course materials repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: materials
      
      - name: Checkout website repository
        uses: actions/checkout@v4
        with:
          repository: leonidas-esquire/gitpolish-course-website
          token: ${{ secrets.SYNC_TOKEN }}
          fetch-depth: 0
          path: website
      
      - name: Sync course materials to website
        run: |
          # Create target directories if they don't exist
          mkdir -p website/public/course-materials
          mkdir -p website/public/docs
          mkdir -p website/public/templates
          mkdir -p website/public/resources
          
          # Sync directories
          rsync -av --delete materials/course-materials/ website/public/course-materials/
          rsync -av --delete materials/docs/ website/public/docs/
          rsync -av --delete materials/templates/ website/public/templates/
          rsync -av --delete materials/resources/ website/public/resources/
          
          # Copy README to website
          cp materials/README.md website/public/COURSE_README.md
      
      - name: Commit and push changes
        working-directory: website
        run: |
          git config user.name "GitPolish Sync Bot"
          git config user.email "sync-bot@gitpolish-course.local"
          
          git add .
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "sync: Update course materials from gitpolish-protocol-course | Automated sync from course materials repository | Updated: course-materials, docs, templates, resources | Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
            git push
          fi
      
      - name: Create sync report
        if: always()
        run: |
          echo "## Sync Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Source**: gitpolish-protocol-course" >> $GITHUB_STEP_SUMMARY
          echo "**Target**: gitpolish-course-website" >> $GITHUB_STEP_SUMMARY
          echo "**Timestamp**: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Synced Directories" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ course-materials/" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ docs/" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ templates/" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ resources/" >> $GITHUB_STEP_SUMMARY
