name: Sync Content to Website

on:
  push:
    branches: [master, main]
    paths:
      - 'course-materials/**'
      - 'resources/**'
      - 'README.md'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC

jobs:
  sync-to-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout materials repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Checkout website repository
        uses: actions/checkout@v4
        with:
          repository: leonidas-esquire/gitpolish-course-website
          token: ${{ secrets.SYNC_TOKEN }}
          path: website-repo
          
      - name: Sync course materials
        run: |
          # Create target directories
          mkdir -p website-repo/public/course-content
          mkdir -p website-repo/public/downloads
          mkdir -p website-repo/public/resources
          
          # Sync course materials
          rsync -av --delete course-materials/ website-repo/public/course-content/
          
          # Sync downloadable documents
          find course-materials -name "*.docx" -exec cp {} website-repo/public/downloads/ \;
          find course-materials -name "*.pdf" -exec cp {} website-repo/public/downloads/ \;
          
          # Sync resources
          if [ -d "resources" ]; then
            rsync -av resources/ website-repo/public/resources/
          fi
          
      - name: Update sync documentation
        run: |
          cd website-repo
          
          # Update sync log
          echo "## Sync $(date -u +%Y-%m-%d\ %H:%M:%S\ UTC)" >> docs/CONTENT_SYNC_LOG.md
          echo "" >> docs/CONTENT_SYNC_LOG.md
          echo "**Source:** gitpolish-protocol-course@${{ github.sha }}" >> docs/CONTENT_SYNC_LOG.md
          echo "**Trigger:** ${{ github.event_name }}" >> docs/CONTENT_SYNC_LOG.md
          echo "**Files synced:** $(find public/course-content public/downloads public/resources -type f 2>/dev/null | wc -l)" >> docs/CONTENT_SYNC_LOG.md
          echo "" >> docs/CONTENT_SYNC_LOG.md
          
          # Update CHANGELOG
          echo "" >> CHANGELOG.md
          echo "### Content Sync - $(date -u +%Y-%m-%d)" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "Synced course materials from gitpolish-protocol-course@${{ github.sha }}" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          
      - name: Commit and push changes
        run: |
          cd website-repo
          git config user.name "GitPolish Sync Bot"
          git config user.email "sync@gitpolish.com"
          git add .
          git diff --staged --quiet || git commit -m "sync: materials → website - course content update

Synced from: gitpolish-protocol-course@${{ github.sha }}
Synced to: gitpolish-course-website
Sync type: ${{ github.event_name }}

[GitPolish Protocol™ Sync System]"
          git push
